/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardGroup: typeof import('bootstrap-vue-next')['BCardGroup']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-next')['BCardTitle']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    ContentItem: typeof import('./src/components/ContentItem.vue')['default']
    EventItem: typeof import('./src/components/events/EventItem.vue')['default']
    EventList: typeof import('./src/components/events/EventList.vue')['default']
    FilterSidebar: typeof import('./src/components/FilterSidebar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeContent: typeof import('./src/components/HomeContent.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LocaleeHeader: typeof import('./src/components/LocaleeHeader.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
